# Generated by Django 5.1.7 on 2025-03-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_ni_rolls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DinnerPlatters',
            new_name='Rice',
        ),
    ]
