# Generated by Django 5.1.7 on 2025-03-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_dinnerplatters_rice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='RegularPizza',
        ),
        migrations.DeleteModel(
            name='SicilianPizza',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
