# Generated by Django 5.1.7 on 2025-03-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_pizza_delete_regularpizza_delete_sicilianpizza_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='large_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='small_price',
        ),
    ]
