# Generated by Django 5.1.7 on 2025-04-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_review_delete_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
