# Generated by Django 5.1.7 on 2025-04-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_rename_comment_review_content_remove_review_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
