# Generated by Django 5.1.7 on 2025-04-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_rename_content_review_review_text_review_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='address',
            new_name='delivery_address',
        ),
        migrations.AddField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('received', 'Order Received'), ('preparing', 'Preparing'), ('baking', 'Baking/Cooking'), ('on_way', 'On the Way'), ('delivered', 'Delivered')], default='received', max_length=20),
        ),
    ]
